# Generated by Django 5.2.1 on 2025-06-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PickupDate', models.DateField()),
                ('PickupTime', models.TimeField()),
                ('PickupLocation', models.CharField(max_length=200)),
                ('DropOff', models.CharField(max_length=200)),
                ('Transfer', models.CharField()),
                ('ExtraTime', models.CharField()),
            ],
        ),
    ]
